---
app: onegateway-sessionmanager
appVersion: v1

sessionManagerDeployment: true

image:
  name: "kubeitglobalsvcauxacrwe.azurecr.io/test/sessionmanager"
  tag: "07102021"

service:
  containerPort: 8000

defaultRouting:
  enabled: true
  hosts: [auto]
  retries:
    attempts: 3
    perTryTimeout: 15s

requestAuthentication:
  enabled: false

authorizationPolicy:
  enabled: false

initContainers:
  - name: wait-for-redis
    image: owncloudci/wait-for
    args:
      - "-it"
      - "onegateway-redis-master:6379"
      - "-t"
      - "30"

health:
  livenessProbe:
    exec:
      command:
        - /bin/sh
        - -c
        - apk add redis; redis-cli -x -h $REDIS_HOST -a $REDIS_PASSWORD ping
    initialDelaySeconds: 5
    periodSeconds: 5

envs:
  - name: ASPNETCORE_ENVIRONMENT
    value: Development
  - name: ASPNETCORE_URLS
    value: http://*:8000
  - name: SESSION_MANAGER_ID
    value: ancris3
  - name: AUTHORITY
    value: https://login.veracity.com/te/dnvglb2cprod.onmicrosoft.com/B2C_1A_SignInWithADFSIdp/v2.0
  - name: SCOPE
    value: https://dnvglb2cprod.onmicrosoft.com/83054ebf-1d7b-43f5-82ad-b2bde84d7b75/user_impersonation
  - name: CLIENT_ID
    value: d94fdc94-6dfa-4c3c-9e1a-21bee90c33d1
  - name: REDIS_HOST
    value: onegateway-redis-master
  - name: REDIS_PORT
    value: 6379
  - name: LOGIN_LANDING_URL
    value: "/"
  - name: LOGOUT_ENDPOINT
    value: https://www.veracity.com/auth/logout
  - name: REPLY_URL_SUFFIX
    value: veracity

envsFrom:
  - name: CLIENT_SECRET
    valueFrom:
      secretKeyRef:
        name: ancris3-session-manager
        key: client-secret
  - name: REDIS_PASSWORD
    valueFrom:
      secretKeyRef:
        name: redis-password
        key: db-password

resources:
  requests:
    cpu: 250m
    memory: 64Mi
  limits:
    cpu: 500m
    memory: 128Mi

secretStore:
  enabled: true
  vaultUrl: "https://kubeit-dev-kv-sh-we.vault.azure.net/"

externalSecrets:
  - name: ancris3-session-manager
    refs:
      - keyName: client-secret
        kvSecretName: ancris3-client-secret
