---
# Workload info
app: onegateway-workload
appVersion: v1

image:
  name: "kubeitglobalsvcauxacrwe.azurecr.io/test/ancris3"
  tag: "main-20210805.6"

serviceAccount:
  enabled: true
  annotations:
    azure.workload.identity/client-id: 8e8c8d25-ccbe-4c50-a864-e0dc2046d46e
    azure.workload.identity/tenant-id: adf10e2b-b6e9-41d6-be2f-c12bb566019c

service:
  containerPort: 8050

additionalPodLabels:
  session-management: frontend
  session-manager-name: onegateway-sessionmanager

defaultRouting:
  enabled: true
  hosts: []
  retries:
    attempts: 3
    perTryTimeout: 2s

destinationRule:
  enabled: true

resources:
  requests:
    cpu: 100m
    memory: 2Gi
  limits:
    cpu: 500m
    memory: 6Gi

envs:
  - name: CLIENT_ID
    value: dd3fabfd-fb4b-4ca3-b079-d45341a56fd3

requestAuthentication:
  enabled: true
  jwtRules:
    - issuer: "https://login.veracity.com/a68572e3-63ce-4bc1-acdc-b64943502e9d/v2.0/"
      jwksUri: "https://login.veracity.com/te/a68572e3-63ce-4bc1-acdc-b64943502e9d/b2c_1a_signinwithadfsidp/discovery/v2.0/keys"
      audiences: [83054ebf-1d7b-43f5-82ad-b2bde84d7b75]
      forwardOriginalToken: true

authorizationPolicy:
  enabled: false
