---
# Source: kubeit-deployment-chart/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: onegateway-workload
  labels:
    app.kubernetes.io/name: onegateway-workload
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: v1
    app.kubernetes.io/managed-by: Helm
    tenant: tenant2
  annotations:
    azure.workload.identity/client-id: 8e8c8d25-ccbe-4c50-a864-e0dc2046d46e
    azure.workload.identity/tenant-id: adf10e2b-b6e9-41d6-be2f-c12bb566019c
---
# Source: kubeit-deployment-chart/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: onegateway-workload
  labels:
    app.kubernetes.io/name: onegateway-workload
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: v1
    app.kubernetes.io/managed-by: Helm
    tenant: tenant2
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: onegateway-workload
    app.kubernetes.io/instance: release-name
---
# Source: kubeit-deployment-chart/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: onegateway-workload
  labels:
    app.kubernetes.io/name: onegateway-workload
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: v1
    app.kubernetes.io/managed-by: Helm
    tenant: tenant2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: onegateway-workload
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: onegateway-workload
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: v1
        app.kubernetes.io/managed-by: Helm
        tenant: tenant2
        session-management: frontend
        session-manager-name: onegateway-sessionmanager
    spec:
      serviceAccountName: onegateway-workload
      terminationGracePeriodSeconds: 30
      containers:
        - name: onegateway-workload
          image: kubeitglobalsvcauxacrwe.azurecr.io/test/ancris3:main-20210805.6
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp
              containerPort: 8050
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 6Gi
            requests:
              cpu: 100m
              memory: 2Gi
          env:
            - name: CLIENT_ID
              value: "dd3fabfd-fb4b-4ca3-b079-d45341a56fd3"
---
# Source: kubeit-deployment-chart/templates/destinationrules.yaml
apiVersion: networking.istio.io/v1
kind: DestinationRule
metadata:
  name: onegateway-workload-dr
  labels:
    app.kubernetes.io/name: onegateway-workload
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: v1
    app.kubernetes.io/managed-by: Helm
    tenant: tenant2
spec:
  host: onegateway-workload.default.svc.cluster.local
  trafficPolicy:
    loadBalancer:
      simple: RANDOM
    tls:
      mode: ISTIO_MUTUAL
---
# Source: kubeit-deployment-chart/templates/requestauthentication.yaml
apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: onegateway-workload-ra
  labels:
    app.kubernetes.io/name: onegateway-workload
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: v1
    app.kubernetes.io/managed-by: Helm
    tenant: tenant2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: onegateway-workload
      app.kubernetes.io/instance: release-name
  jwtRules:
    - audiences:
      - 83054ebf-1d7b-43f5-82ad-b2bde84d7b75
      forwardOriginalToken: true
      issuer: https://login.veracity.com/a68572e3-63ce-4bc1-acdc-b64943502e9d/v2.0/
      jwksUri: https://login.veracity.com/te/a68572e3-63ce-4bc1-acdc-b64943502e9d/b2c_1a_signinwithadfsidp/discovery/v2.0/keys
---
# Source: kubeit-deployment-chart/templates/virtualservice.yaml
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: onegateway-workload-dev033-kubeit-dnv-com-ext
  labels:
    app.kubernetes.io/name: onegateway-workload
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: v1
    app.kubernetes.io/managed-by: Helm
    tenant: tenant2
spec:
  hosts:
    - onegateway-workload.dev033.kubeit.dnv.com
  gateways:
    - istio-system/global-https-external-default-gateway
  http:
    - match:
      - uri:
          prefix: /
      route:
        - destination:
            host: onegateway-workload.default.svc.cluster.local
            port:
              number: 80
      retries:
        attempts: 3
        perTryTimeout: 2s
---
# Source: kubeit-deployment-chart/templates/virtualservice.yaml
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: onegateway-workload-mesh
spec:
  hosts:
    - onegateway-workload.default.svc.cluster.local
  gateways:
    - mesh
  http:
    - route:
      - destination:
          host: onegateway-workload.default.svc.cluster.local
      retries:
        attempts: 3
        perTryTimeout: 2s
